### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by MadMikeyB** [marianvlad/nova-env-card#1]
I just wanted to know what the security considerations were when creating this package?

Exposing the environment file to a web based administration panel can never be a good thing, surely?

Additionally, if more than one user has access to Nova, and only one is the system administrator (think WordPress, Editors and Administrators) - how do you protect the system from abuse by those with a lower access level?

I understand the desire to create packages for nova to get your name out there, however I would also like to know your particular use case for this package as well. 

Do you not consider this to be a gaping security hole in any site on which it is installed?

**Comment by marianvlad** [comment]
I don't make packages to promote my name. Everyone is free to make any packages they want. The user can decide the use case for them, maybe they don't want to press 10 buttons in Forge or connect through ssh to edit something in .env. And from what I saw, nobody secured their packages 100%, especially routes.

Now you can do something like that.
```php
(new \Marianvlad\NovaEnvCard\NovaEnvCard)->canSee(function ($request) {
    return $request->user()->role == 'admin';
})
```

**Comment by paulmichaeldev** [comment]
The security risk comes from providing access to, and ability to edit, the main site configuration file in a web admin panel which could have unknown vulnerabilities. It's got nothing to do with the concept of securing routes.

These things are not convenient to edit or access for good reason.

**Comment by MadMikeyB** [comment]
@marianvlad Appreciate the response, I apologize if it appeared as if I was insinuating that you were merely chasing fame. _That_ was not my intention.

I appreciate the time, effort and passion which has gone into this package. You obviously see a need for this package and are using it, I merely wanted to point out the fact that perhaps exposing the .env file to users through a web administration panel is not the wisest thing to do.

Again I appreciate you addressing one of my concerns through the above code snippet, however I still believe the concept as a whole to be flawed.

I would say that it is only one step removed to leaving your .env file in the `public` directory for the world to see. If your application is compromised through XSS or SQL Injection, the attacker automatically has access to the .env file, and as such, your database credentials at the very least, and your production stripe keys in the worst case scenario.

However, I do not mean to start an argument with you here. I do not use this package and as such I have no horse in this race. I simply wanted to raise this as an issue. If you disagree, please feel free to close the issue.

Thanks!

**Comment by marianvlad** [comment]
@MadMikeyB I agree with you 100%, you are right. What do you think about https://laravel-news.com/edit-your-environment-files-through-the-browser-with-brotzka-env-editor ?

**Comment by ollieread** [comment]
@marianvlad I think the concern is that there's no discernable reason why anyone would want to edit an `.env` file within the admin area of the site that is using that `.env`. 

Actually no, let me correct that.

There is no discernable reason why anyone SHOULD be able to edit an `.env` file within the admin area of the site that is using that `.env`. 

Don't get me wrong, it's good work, just concerning. As developers we should be promoting best practices, and we have a duty to point others in the right direction.

To quote the greatest of Jeffs;

> Your scientists were so preoccupied with whether or not they could, they didn’t stop to think if they should.

**Comment by MadMikeyB** [comment]
@marianvlad I have the exact same problems with that as I do with this unfortunately. 

In my opinion, the **only** acceptable way to edit the .env file outside of a CLI is through Forge, and that's only because they offer things like 2FA to secure your account. Even then I dislike that very much.
